---
title: "Plaatjes"
author: "Eva Rombouts"
date: "2022-10-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
source("scripts/LadenEnOpschonen.R")
source("scripts/PersoneelsSamenstelling.R")

coloriet <- 'Stichting Coloriet'
amsta <- 'Stichting Amsta'
zgao <- 'Stichting Zorggroep Amsterdam-Oost'
samen <- 'STICHTING WOONZORGGROEP SAMEN'
quarijn <- 'Stichting QuaRijn'

org <- quarijn
hl <- ps [ps$organisatie == org, ]


# pk naar grootte ----
ps %>%
  ggplot (aes(nClienten, pkPerClient, size = pPNIL)) +
  geom_point(alpha = 0.4) +
  geom_smooth(method = "lm") +
  geom_point(
    aes(nClienten, pkPerClient),
    data = hl,
    colour = "red",
    alpha = 0.5
  ) +
  scale_x_log10() +
  labs (title = "Personeelskosten per client naar grootte organisatie",
        subtitle = paste("Highlighted: ", org),
        x = "aantal clienten",
        y = "personeelskosten per client per jaar (EUR)") +
  theme_bw()

# pk naar PNIL ----
ps %>%
  ggplot (aes(nClienten, nCpFTE, size = FTEperCt)) +
  geom_point(alpha = 0.4) +
  geom_smooth(method = "lm") +
  geom_point(
    aes(nClienten, nCpFTE),
    data = hl,
    colour = "red",
    alpha = 0.5
  ) +
  scale_x_log10()+
  labs (title = "Aantal clienten per FTE naar grootte organisatie",
        subtitle = paste("Highlighted: ", org),
        x = "aantal clienten",
        y = "aantal clienten per FTE") +
  theme_bw()

# niveaumix ----
# pivot long om waarden naast elkaar te kunnen weergeven
ps_long <- ps %>%
  pivot_longer(
    cols = c(
      pNiv1,
      pNiv2,
      pNiv3,
      pNiv4,
      pNiv5,
      pNiv6,
      pBehandel,
      pOverig,
      pLeerling
    ),
    names_to = "functie",
    values_to = "pFunctie"
  ) %>%
  select (organisatie, nClienten, functie, pFunctie) %>%
  filter (str_detect(functie, "^pNiv")|functie == "pBehandel") %>%
  mutate (Grootte = ordered(cut(
    nClienten,
    breaks = c(-Inf, 50, 300, Inf),
    labels = c("<50", "50-300", ">300")
  )))

hl <- ps_long [ps_long$organisatie == org,]

ps_long %>%
  ggplot (aes(functie, pFunctie)) +
  geom_boxplot(fill = "thistle", notch = T) +
  geom_point(
    aes(functie, pFunctie),
    data = hl,
    color = "red",
    size = 3
  ) +
  facet_wrap( ~ Grootte) +
  labs (
    title = "Niveaumix naar grootte organisatie",
    subtitle = paste("Highlighted: ", org),
    x = "functie / niveau",
    y = "percentage van zorgmedewerkers"
  ) +
  theme_bw()

```

